### ISSUE TITLE
PulsePointLite adapter giving alias error, even when not manually aliased.

### ISSUE THREAD

**Issue by tr-coull** [prebid/Prebid.js#2139]
## Type of issue
Bug.

## Description
_Using PrebidJS v0.29.0_
I would like to switch from using the PulsePoint adapter to using the PulsePointLite adapter. So that we can still use the name "pulsepoint" elsewhere in our systems, I will be aliasing 'pulseLite' as 'pulsepoint', however, before even doing this, the unmodified 'Lite' adapter is giving this error: 

> "adaptermanager.aliasBidAdapter: pulseLite bidder does not currently support aliasing."

It looks like this is caused by this line at the bottom of pulsepointLiteBidAdapter.js:
`adaptermanager.aliasBidAdapter('pulseLite', 'pulsepointLite');`
(https://github.com/prebid/Prebid.js/blob/0.29.0/modules/pulsepointLiteBidAdapter.js#L299)

Why is this line in the unmodified adapter causing an error, and how can I alias the Lite adapter as "pulsepoint"? Taking that line out and trying to alias as a different name elsewhere still causes the same error.

## Steps to reproduce
Include the pulsepointLite adapter in your build.

## Platform details
Using PrebidJS v0.29.0, Chrome 63, OSX 10.12.6.

**Comment by anand-venkatraman** [comment]
Hi, I am an engineer at PulsePoint, I will take a look at this and will reply back.
Thanks.

**Comment by anand-venkatraman** [comment]
Hi, I am confirming this is an issue with the PulsePointLiteAdapter when using the alias `pulsepointLite`. However, you can use the `pulseLite` alias, and it will work without any issues. Here is a [test page](http://projects.contextweb.com/av/prebid-issue/?pbjs_debug=true). 

This issue was subsequently addressed in 0.30 build.

**Comment by tr-coull** [comment]
@anand-venkatraman Thanks for that helpful info. I was worried that the error log still occurs with no modifications to the 0.29.0 adapter, but this only occurs when logging/debug is enabled in prebidjs. As we are not currently able to update the core library version, we can modify our version of the Lite adapter to be registered with the name 'pulsepoint' so our systems recognise it that way and do not need to alias the adapter.
