### ISSUE TITLE
Internet Explorer 11 and older compatibility.

### ISSUE THREAD

**Issue by pitns** [prebid/Prebid.js#463]
Guys,

We have been notified by our users who use prebid 0.9 with Internet Explorer 11 and older that some functionalities are not working correctly. We investigated it and found out that prebid library is adding methods into Array prototype object therefore every array that is using loop format "for in" is going to loop through those methods as well as they were their elements causing very difficult to debug and address issues. We had to disable prebid features for all IE users for now. Can that be addressed?

Example:
`Include prebid library.
var testArray = ['bold', 'italic', 'underline', 'justifyleft'];
for (test in testArray) {
    alert(test); //Example: Return "find" index too which is not present in the array on IE.
}
`

The bug and potentioal fix are explained on below page:
http://stackoverflow.com/questions/35135127/adding-a-function-to-array-prototype-in-ie-results-in-it-being-pushed-in-to-ever

Can you please look into it and let us know if anything can be done to fix it on your end?

**Comment by mkendall07** [comment]
@pitns 
Thanks for the info. This looks particularly nasty. We'll review and let you know. We would make a change to master, as we won't be releasing a prior version. Thanks

**Comment by mkendall07** [comment]
This is resolved in master

**Comment by internetchris** [comment]
Curious, did this resolve this issue as well? 
![screen shot on 2016-08-04 at 09-32-55](https://cloud.githubusercontent.com/assets/45402/17407970/89a2684e-5a26-11e6-9cee-b5454cc6f9b2.png)

I can open a new issue if not. IE 11, Prebid 10.

**Comment by protonate** [comment]
@internetchris the `includes` polyfill fix for IE has been merged to master with PR #464.

**Comment by internetchris** [comment]
Hi Nate,

Indeed, thank you. It seems this uses Object.defineProperty, which doesn't
appear to be supported in IE8. Is this an oversight or is prebid ending
support for IE8?

Comment on supported browsers:
https://github.com/prebid/Prebid.js/issues/445

Browser Support:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by internetchris** [comment]
@protonate - I wanted to come back to my question from nearly a year ago. I've noticed that IE8 is still an issue with Object.defineProperty. Are there any plans to fix this, or another issue thread that describes whether or not Prebid will continue to support IE8? As a developer, I would love if IE8 went away, but we still have an international user base that uses IE8 and thus  affects ad revenue. 

![screen shot on 2017-06-06 at 14-28-23](https://user-images.githubusercontent.com/45402/26852866-899b3742-4ac4-11e7-87e6-70406ec3520f.png)

**Comment by protonate** [comment]
Hi @internetchris our browser support has been at IE9+ for some time: https://github.com/prebid/Prebid.js#supported-browsers

We definitely don't want to bloat the core codebase with polyfills, shims & fixes for IE8 or even IE9 at this point. That said for pubs where IE8 support is wanted perhaps a prebid-ie8 repo/package could be included in the build. Creating this would likely need to largely depend on the community as core team resources are stretched as it is.
